### ISSUE TITLE
python3.5 error

### ISSUE THREAD

**Issue by loretoparisi** [openai/gpt-2-output-dataset#14]
I get this error when using `python3.5`:
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 144, in _get_module_details
    code = loader.get_code(mod_name)
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/mnt/Data/ubuntu/gpt-2-output-dataset/detector/train.py", line 133
    records = [record for v in range(votes) for record in tqdm(loader, desc=f'Preloading data ... {v}',
```

**Comment by jongwook** [comment]
The stacktrace is incomplete I think, but it's probably coming from the f-string which is supported in 3.6 or later.

We do not have plan to support 3.5 at this point. I'd suggest using an [Anaconda distribution](https://www.anaconda.com/distribution/#download-section) rather than the Python that comes with your OS.
